export const CHANGE_OLD_SEARCH_LIST = 'CHANGE_OLD_SEARCH_LIST'
export const CHANGE_SEARCH_FIND_LIST = 'CHANGE_SEARCH_FIND_LIST'
export const CHANGE_HOT_SEARCH_VEDIO_LIST = 'CHANGE_HOT_SEARCH_VEDIO_LIST'
export const CHANGE_HOT_SEARCH_GAME_LIST = 'CHANGE_HOT_SEARCH_GAME_LIST'
export const CHANGE_SEARCH_ITEM_LIST = 'CHANGE_SEARCH_ITEM_LIST'

