// export const CHANGE_BANNER = 'CHANGE_BANNER'
export const CHANGE_IDEA_DETAIL_ENTER_GUZHANG = 'CHANGE_IDEA_DETAIL_ENTER_GUZHANG'
export const  CHANGE_IDEA_DETAIL_GUZHANG_NUMBER='CHANGE_IDEA_DETAIL_GUZHANG_NUMBER'
export const  CHANGE_IDEA_DETAIL_ID='CHANGE_IDEA_DETAIL_ID'

// export const CHANGE_ENTER_LOADING = 'CHANGE_ENTER_LOADING'

